services:
  - type: web
    name: vet-clinic-ai-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
