services:
  - type: web
    name: vet-clinic-ai-chatbot
    runtime: python
    buildCommand: |
      python3.11 -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python -m gunicorn server:app -c gunicorn.conf.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: ADMIN_WHATSAPP_NUMBER
        sync: false
